project_id = "gzpsjrfghqypgescloed"

[functions.send-email]
verify_jwt = false

[functions.brise-auth]
verify_jwt = false

[functions.brise-devices]
verify_jwt = false

[functions.brise-control]
verify_jwt = false

[functions.smartthings-auth]
verify_jwt = false

[functions.smartthings-control]
verify_jwt = false

[functions.smartthings-devices]
verify_jwt = false

[functions.smartthings-sync]
verify_jwt = false

[functions.collect-energy-data]
verify_jwt = false
